/* eslint-disable no-restricted-globals */
import {precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL} from 'workbox-precaching';
import {clientsClaim} from 'workbox-core';
import {registerRoute} from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin }  from 'workbox-expiration';
import { FILES } from './file-list';
const CACHE = 'vr-videos-v1';


// Skip waiting to activate new service worker immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by the build process.
// The __WB_MANIFEST is replaced at build time with the list of URLs to precache.
precacheAndRoute(self.__WB_MANIFEST || []);

// Clean up outdated caches automatically.
cleanupOutdatedCaches();

// Set up App Shell-style routing, so that all navigation requests
// are served with our precached index.html (from __WB_MANIFEST).
const appShellHandler = createHandlerBoundToURL(
  /* URL of app shell */ 'index.html'
);
// Register navigation route: handle all navigation requests
registerRoute(
  // Return true for navigation requests
  ({ request, url }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    // Exclude API routes or static file extensions
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(/\.[^/?]+$/)) return false;
    return true;
  },
  appShellHandler
);

registerRoute(
  // Set video file cache strategy
  ({request, url}) => request.destination === 'video' || url.pathname.endsWith('.m3u8') || url.pathname.endsWith('.ts') || request.destination === 'image',
  new CacheFirst({
    cacheName: CACHE,
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: 30 * 24 * 60 * 60, // Cache for 30 days
      }),
    ]
  })
);

// Set to cache js and css files
registerRoute(
  ({request, url}) => request.destination === 'script' || request.destination === 'style',
  new CacheFirst({
    cacheName: CACHE,
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: 30 * 24 * 60 * 60, // Cache for 30 days
      }),
    ]
  })
);

// Cache manifest.json
registerRoute(
  ({request, url}) => url.pathname.endsWith('manifest.json'),
  new CacheFirst({
    cacheName: CACHE,
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: 30 * 24 * 60 * 60, // Cache for 30 days
      }),
    ]
  })
);

self.addEventListener('install', event => {
  /* cache each file one-by-one so we can stream progress */
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      let totalBytes = 0, loadedBytes = 0;

      // First pass: HEAD requests to know sizes
      const sizes = {};
      for (const url of FILES) {
        // Check if the file is already cached
        const cachedResponse = await cache.match(url);
        if (cachedResponse) {
          sizes[url] = Number(cachedResponse.headers.get('content-length') || 0);
          totalBytes += sizes[url];
          continue;
        }
        // If not cached, make a HEAD request to get the size
        const head = await fetch(url, {method: 'HEAD'});
        sizes[url] = Number(head.headers.get('content-length') || 0);
        totalBytes += sizes[url];
      }

      // Second pass: stream each file and accumulate progress
      for (const url of FILES) {
        // Check if the file is already cached
        const cachedResponse = await cache.match(url);
        if (cachedResponse) {
          loadedBytes += sizes[url];
          // broadcast % to every client
          const pct = Math.round((loadedBytes / totalBytes) * 100);
          (await self.clients.matchAll({includeUncontrolled: true}))
            .forEach(c => c.postMessage({type: 'CACHE_PROGRESS', pct}));
          continue;
        }
        // If not cached, stream the file
        const response = await fetch(url);
        const reader = response.body.getReader();
        const chunks = [];
        let received = 0;

        while (true) {
          const {done, value} = await reader.read();
          if (done) break;
          chunks.push(value);
          received += value.length;
          loadedBytes += value.length;

          // broadcast % to every client
          const pct = Math.round((loadedBytes / totalBytes) * 100);
          (await self.clients.matchAll({includeUncontrolled: true}))
            .forEach(c => c.postMessage({type: 'CACHE_PROGRESS', pct}));
        }

        const fullBlob = new Blob(chunks, {type: response.headers.get('content-type')});
        await cache.put(url, new Response(fullBlob, {headers: response.headers}));
      }

      // tell UI we're finished
      (await self.clients.matchAll({includeUncontrolled: true}))
        .forEach(c => c.postMessage({type: 'CACHE_DONE'}));
    })()
  );
});

self.addEventListener('fetch', event => {
  const {request} = event;
  if (request.url.includes('mp4') || request.url.includes('wav') || request.url.includes('m3u8') || request.url.includes('ts') || request.url.includes('manifest.json')) {
    event.respondWith(
      caches.match(request).then(r => r || fetch(request))
    );
  }
});

